import {state} from "./state.js";import {connectFeishu,readContext,readSelectedRecords} from "./feishu.js";import {loadTemplates,exportTemplate} from "./templates.js";import {writeBridge,openDesigner} from "./bridge.js";import {renderTemplateToHtml,hydrateCodes} from "./renderer.js";
const $=id=>document.getElementById(id);let toastTimer;
function toast(msg){const n=$("toast");n.textContent=msg;n.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove("show"),1600)}
function status(text,type=""){const n=$("sdkState");n.textContent=text;n.className="status-pill "+type}
function activeTemplate(){return state.templates.find(t=>t.id===state.activeTemplateId)||state.templates[0]}
function fillTemplates(){const s=$("templateSelect");s.innerHTML="";state.templates.forEach(t=>{const o=document.createElement("option");o.value=t.id;o.textContent=t.name;s.appendChild(o)});if(state.activeTemplateId)s.value=state.activeTemplateId}
function renderRecord(){const rec=state.record;$("recordEmpty").classList.toggle("hidden",!!rec);$("recordBox").classList.toggle("hidden",!rec);if(!rec){$("selectionText").textContent="未选择记录";return}$("recordTitle").textContent=rec.data?.订单编号||rec.data?.["订单号"]||"当前记录";const box=$("recordFields");box.innerHTML="";Object.entries(rec.data||{}).slice(0,12).forEach(([k,v])=>{const row=document.createElement("div");row.className="record-field";row.innerHTML='<span class="k"></span><span class="v"></span>';row.children[0].textContent=k;row.children[1].textContent=v||"—";box.appendChild(row)});$("selectionText").textContent="已选择 1 条记录";renderQuickPreview()}
function renderQuickPreview(){const tpl=activeTemplate();$("previewTitle").textContent=tpl?.name||"打印模板";$("previewSubtitle").textContent=state.record?"已载入当前记录":"选择记录后显示真实数据";const lines=$("previewLines");lines.innerHTML="";for(let i=0;i<5;i++){const d=document.createElement("div");d.className="preview-line";d.style.width=(96-i*8)+"%";lines.appendChild(d)}}
async function refresh(){try{$("statusText").textContent="正在读取飞书数据";const c=await connectFeishu();if(!c.connected){state.connected=false;status("演示模式","warn");$("statusText").textContent="未连接飞书 SDK";renderRecord();return}state.connected=true;state.sdk=c.bitable;status("已连接","success");const ctx=await readContext(c.bitable);state.selection=ctx.selection;state.table=ctx.table;state.fields=ctx.fields;state.record=ctx.record;state.selectedRecords=await readSelectedRecords(c.bitable,ctx.table,ctx.fields);writeBridge({fields:state.fields,record:state.record,selection:state.selection});renderRecord();$("statusText").textContent="数据已同步"}catch(err){console.error(err);status("连接异常","error");$("statusText").textContent="读取失败";toast("读取飞书数据失败")}}
function printRecords(records){const tpl=activeTemplate();if(!tpl)return;const host=document.createElement("div");host.className="print-host";host.style.position="fixed";host.style.inset="0";host.style.zIndex="9999";host.style.background="#fff";host.style.overflow="auto";host.innerHTML=records.map(r=>renderTemplateToHtml(tpl,r.data||{})).join("");document.body.appendChild(host);hydrateCodes(host).finally(()=>setTimeout(()=>{window.print();host.remove()},120))}
async function init(){state.templates=loadTemplates();state.activeTemplateId=state.templates[0]?.id||null;fillTemplates();$("templateSelect").addEventListener("change",e=>{state.activeTemplateId=e.target.value;renderQuickPreview()});$("refreshData").addEventListener("click",refresh);$("openDesigner").addEventListener("click",()=>{writeBridge({fields:state.fields,record:state.record,selection:state.selection});openDesigner(state.activeTemplateId)});$("exportTemplate").addEventListener("click",()=>exportTemplate(activeTemplate()));$("printCurrent").addEventListener("click",()=>state.record?printRecords([state.record]):toast("请先选择一条记录"));$("printSelected").addEventListener("click",()=>state.selectedRecords.length?printRecords(state.selectedRecords):toast("当前没有可打印的选择记录"));window.addEventListener("focus",()=>{state.templates=loadTemplates();fillTemplates();renderQuickPreview()});
renderQuickPreview();
await refresh();
// Follow the active Base selection immediately; polling remains as a fallback.
try{
  if(state.sdk?.base?.onSelectionChange){
    state.sdk.base.onSelectionChange(()=>refresh());
  }
}catch(err){console.warn("selection listener unavailable",err)}
setInterval(refresh,4000)}
init();
