import {state,uid} from "./state.js";import {loadTemplates,saveTemplates,createTemplate} from "./templates.js";import {readBridge} from "./bridge.js";import {renderTemplateToHtml,hydrateCodes} from "./renderer.js";
const MM=96/25.4,$=id=>document.getElementById(id);let selected=new Set(),zoom=75,grid=true,snap=true,preview=false,history=[],hIndex=-1,dragType=null,toastTimer;
function toast(m){const n=$("toast");n.textContent=m;n.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove("show"),1500)}
function current(){return state.templates.find(t=>t.id===state.activeTemplateId)}
function pushHistory(){const t=current();if(!t)return;history=history.slice(0,hIndex+1);history.push(JSON.stringify(t));if(history.length>60)history.shift();hIndex=history.length-1;updateUndo()}
function restore(i){if(i<0||i>=history.length)return;const old=current();const parsed=JSON.parse(history[i]);const idx=state.templates.findIndex(t=>t.id===old.id);state.templates[idx]=parsed;hIndex=i;renderAll();updateUndo()}
function updateUndo(){$("undoBtn").disabled=hIndex<=0;$("redoBtn").disabled=hIndex>=history.length-1}
function load(){state.templates=loadTemplates();const qs=new URLSearchParams(location.search).get("template");state.activeTemplateId=(qs&&state.templates.some(t=>t.id===qs))?qs:state.templates[0]?.id;const bridge=readBridge();state.fields=bridge?.fields||[];state.record=bridge?.record||null;populateFields();renderAll();pushHistory()}
function populateFields(){const list=$("fieldList"),sel=$("propField");list.innerHTML="";sel.innerHTML='<option value="">未绑定</option>';for(const f of state.fields){const item=document.createElement("div");item.className="field-item";item.draggable=true;item.dataset.field=f.name;item.innerHTML="<b></b><small></small>";item.children[0].textContent=f.name;item.children[1].textContent="字段类型 "+f.type;item.addEventListener("dragstart",e=>{dragType="field:"+f.name;e.dataTransfer.setData("text/plain",dragType)});item.addEventListener("dblclick",()=>addElement("field",30,30,f.name));list.appendChild(item);const o=document.createElement("option");o.value=f.name;o.textContent=f.name;sel.appendChild(o)}}
function renderAll(){const t=current();if(!t)return;$("templateName").value=t.name;$("pageW").value=t.page.width;$("pageH").value=t.page.height;$("safeArea").value=t.page.safeArea??4;applyPage(false);renderElements();renderLayers();syncProps();$("selectionState").textContent=(t.elements?.length||0)+" 个元素"}
function applyPage(save=true){const t=current();if(!t)return;const w=Math.max(20,Number($("pageW").value)||215),h=Math.max(20,Number($("pageH").value)||140),safe=Math.max(0,Number($("safeArea").value)||0);t.page.width=w;t.page.height=h;t.page.safeArea=safe;const p=$("printPage");p.style.width=w*MM+"px";p.style.height=h*MM+"px";const s=$("safeGuide");s.style.inset=safe*MM+"px";$("pageInfo").textContent=w+" × "+h+" mm";drawRulers(w,h);if(save){t.updatedAt=Date.now();pushHistory();autoSave();toast("页面尺寸已更新")}}
function drawRulers(w,h){const tr=$("topRuler"),lr=$("leftRuler");tr.innerHTML="";lr.innerHTML="";tr.style.width=w*MM+"px";lr.style.height=h*MM+"px";for(let m=0;m<=w;m+=10){const n=document.createElement("span");n.textContent=m;n.style.cssText="position:absolute;left:"+(m*MM)+"px;top:5px";tr.appendChild(n)}for(let m=0;m<=h;m+=10){const n=document.createElement("span");n.textContent=m;n.style.cssText="position:absolute;top:"+(m*MM)+"px;left:3px;transform:rotate(-90deg);transform-origin:left top";lr.appendChild(n)}}
function defaults(type,field=""){const b={id:uid("el"),type,x:20,y:20,w:45,h:10,text:"",field,fontSize:11,fontWeight:"400",align:"left",locked:false,hidden:false};if(type==="text"){b.text="双击或在右侧修改文字";b.w=58}if(type==="field"){b.text="{{"+(field||"字段")+"}}";b.field=field;b.w=50}if(type==="image"){b.w=30;b.h=25}if(type==="table"){b.w=115;b.h=38;b.columns=["商品名称","商品属性","数量","价格"]}if(type==="barcode"){b.w=62;b.h=20;b.field=field||"订单编号";b.showText=true}if(type==="qrcode"){b.w=25;b.h=25;b.field=field||"订单编号"}if(type==="line"){b.w=70;b.h=.5}if(type==="container"){b.w=70;b.h=34}return b}
function addElement(type,x=25,y=25,field=""){const t=current();const e=defaults(type,field);e.x=x;e.y=y;t.elements.push(e);selected=new Set([e.id]);renderElements();renderLayers();syncProps();pushHistory();autoSave();toast("已添加组件")}
function renderElements(){const p=$("printPage");p.querySelectorAll(".design-element").forEach(n=>n.remove());const t=current();for(const e of t.elements){const n=document.createElement("div");n.className="design-element "+e.type+"-el"+(selected.has(e.id)?" selected":"")+(e.locked?" locked":"")+(e.hidden?" hidden-element":"");n.dataset.id=e.id;n.style.left=e.x*MM+"px";n.style.top=e.y*MM+"px";n.style.width=e.w*MM+"px";n.style.height=Math.max(1,e.h*MM)+"px";n.style.fontSize=(e.fontSize||11)+"px";n.style.fontWeight=e.fontWeight||400;n.style.textAlign=e.align||"left";content(n,e);n.addEventListener("pointerdown",ev=>startMove(ev,e));n.addEventListener("click",ev=>{ev.stopPropagation();if(ev.shiftKey){selected.has(e.id)?selected.delete(e.id):selected.add(e.id)}else selected=new Set([e.id]);renderElements();renderLayers();syncProps()});n.addEventListener("contextmenu",ev=>showContext(ev,e.id));if(selected.has(e.id)&&!preview&&!e.locked)addHandles(n,e);p.appendChild(n)}}
function content(n,e){const data=state.record?.data||{};if(e.type==="text")n.textContent=e.text||"";else if(e.type==="field")n.textContent=preview?((e.label||"")+(data[e.field]??"")):(e.text||"{{"+(e.field||"字段")+"}}");else if(e.type==="image")n.textContent="图片";else if(e.type==="container"||e.type==="line"){}else if(e.type==="barcode")n.innerHTML='<div class="barcode-bars"></div>';else if(e.type==="qrcode"){}else if(e.type==="table"){const cols=e.columns||["商品名称","数量"];n.innerHTML="<table><thead><tr>"+cols.map(c=>"<th>"+c+"</th>").join("")+"</tr></thead><tbody><tr>"+cols.map(c=>"<td>"+(preview?(data[c]??""):"{{"+c+"}}")+"</td>").join("")+"</tr></tbody></table>"}}
function addHandles(n,e){for(const d of ["nw","n","ne","e","se","s","sw","w"]){const h=document.createElement("span");h.className="resize-handle "+d;h.dataset.dir=d;h.addEventListener("pointerdown",ev=>startResize(ev,e,d));n.appendChild(h)}}
function startMove(ev,e){if(preview||e.locked||ev.target.classList.contains("resize-handle"))return;ev.preventDefault();ev.stopPropagation();if(!selected.has(e.id))selected=ev.shiftKey?new Set([...selected,e.id]):new Set([e.id]);const sx=ev.clientX,sy=ev.clientY,start=[...selected].map(id=>{const x=current().elements.find(v=>v.id===id);return{x,id,ox:x.x,oy:x.y}}),factor=zoom/100;const move=m=>{let dx=(m.clientX-sx)/factor/MM,dy=(m.clientY-sy)/factor/MM;if(snap){dx=Math.round(dx*2)/2;dy=Math.round(dy*2)/2}for(const a of start){a.x.x=Math.max(0,a.ox+dx);a.x.y=Math.max(0,a.oy+dy)}renderElements();syncProps()};const up=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up);pushHistory();autoSave()};addEventListener("pointermove",move);addEventListener("pointerup",up)}
function startResize(ev,e,dir){ev.preventDefault();ev.stopPropagation();const sx=ev.clientX,sy=ev.clientY,o={x:e.x,y:e.y,w:e.w,h:e.h},factor=zoom/100;const move=m=>{let dx=(m.clientX-sx)/factor/MM,dy=(m.clientY-sy)/factor/MM;if(snap){dx=Math.round(dx*2)/2;dy=Math.round(dy*2)/2}if(dir.includes("e"))e.w=Math.max(2,o.w+dx);if(dir.includes("s"))e.h=Math.max(.5,o.h+dy);if(dir.includes("w")){e.x=o.x+dx;e.w=Math.max(2,o.w-dx)}if(dir.includes("n")){e.y=o.y+dy;e.h=Math.max(.5,o.h-dy)}renderElements();syncProps()};const up=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up);pushHistory();autoSave()};addEventListener("pointermove",move);addEventListener("pointerup",up)}
function selectedOne(){if(selected.size!==1)return null;return current().elements.find(e=>selected.has(e.id))}
function syncProps(){const e=selectedOne();$("noSelection").classList.toggle("hidden",!!e);$("props").classList.toggle("hidden",!e);if(!e)return;for(const [id,k] of [["propX","x"],["propY","y"],["propW","w"],["propH","h"]])$(id).value=Math.round(e[k]*10)/10;$("propText").value=e.text||"";$("propField").value=e.field||"";$("propFontSize").value=e.fontSize||11;$("propWeight").value=e.fontWeight||"400";$("lockBtn").textContent=e.locked?"解锁":"锁定";$("hideBtn").textContent=e.hidden?"显示":"隐藏";document.querySelectorAll("[data-align]").forEach(b=>b.classList.toggle("active",b.dataset.align===(e.align||"left")))}
function updateProps(){const e=selectedOne();if(!e)return;e.x=Number($("propX").value)||0;e.y=Number($("propY").value)||0;e.w=Math.max(.5,Number($("propW").value)||1);e.h=Math.max(.5,Number($("propH").value)||1);e.text=$("propText").value;e.field=$("propField").value;e.fontSize=Math.max(6,Number($("propFontSize").value)||11);e.fontWeight=$("propWeight").value;if(e.type==="field"&&e.field)e.text="{{"+e.field+"}}";renderElements()}
function renderLayers(){const list=$("layerList");list.innerHTML="";[...current().elements].reverse().forEach(e=>{const r=document.createElement("div");r.className="layer-row"+(selected.has(e.id)?" active":"");r.innerHTML='<button title="显示/隐藏">'+(e.hidden?"○":"●")+'</button><span></span><button title="锁定">'+(e.locked?"🔒":"◇")+"</button>";r.children[1].textContent=(e.type==="field"?e.field:e.text)||e.type;r.children[0].onclick=()=>{e.hidden=!e.hidden;renderElements();renderLayers();autoSave()};r.children[2].onclick=()=>{e.locked=!e.locked;renderElements();renderLayers();autoSave()};r.onclick=ev=>{if(ev.target.tagName==="BUTTON")return;selected=new Set([e.id]);renderElements();renderLayers();syncProps()};list.appendChild(r)})}
function autoSave(){const t=current();t.name=$("templateName").value.trim()||"未命名模板";t.updatedAt=Date.now();saveTemplates(state.templates);$("saveState").innerHTML="<i></i>已自动保存"}
function del(){if(!selected.size)return;current().elements=current().elements.filter(e=>!selected.has(e.id));selected.clear();renderAll();pushHistory();autoSave()}
function duplicate(){const els=current().elements.filter(e=>selected.has(e.id));const ids=[];for(const e of els){const c=structuredClone(e);c.id=uid("el");c.x+=4;c.y+=4;c.locked=false;current().elements.push(c);ids.push(c.id)}selected=new Set(ids);renderAll();pushHistory();autoSave()}
function moveLayer(front){const t=current(),ids=[...selected];const take=t.elements.filter(e=>ids.includes(e.id)),rest=t.elements.filter(e=>!ids.includes(e.id));t.elements=front?[...rest,...take]:[...take,...rest];renderAll();pushHistory();autoSave()}
function toggleKey(k){for(const e of current().elements.filter(e=>selected.has(e.id)))e[k]=!e[k];renderAll();pushHistory();autoSave()}
function showContext(ev,id){ev.preventDefault();selected=new Set([id]);renderElements();renderLayers();syncProps();const m=$("contextMenu");m.style.left=ev.clientX+"px";m.style.top=ev.clientY+"px";m.classList.remove("hidden")}
function setZoom(v){zoom=Math.max(40,Math.min(160,Number(v)));$("zoomLayer").style.transform="scale("+(zoom/100)+")";$("zoomRange").value=zoom;$("zoomText").textContent=zoom+"%"}
function setPreview(v){preview=v;document.body.classList.toggle("preview-mode",v);$("previewBtn").textContent=v?"退出预览":"实际预览";renderElements()}
async function testPrint(){const t=current(),host=document.createElement("div");host.className="print-host";host.style.cssText="position:fixed;inset:0;z-index:9999;background:#fff";host.innerHTML=renderTemplateToHtml(t,state.record?.data||{});document.body.appendChild(host);await hydrateCodes(host);setTimeout(()=>{window.print();host.remove()},100)}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("componentsTab").classList.toggle("hidden",b.dataset.tab!=="components");$("fieldsTab").classList.toggle("hidden",b.dataset.tab!=="fields")});document.querySelectorAll(".rtab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".rtab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("propsTab").classList.toggle("hidden",b.dataset.rtab!=="props");$("layersTab").classList.toggle("hidden",b.dataset.rtab!=="layers")});
document.querySelectorAll(".component-palette button").forEach(b=>{b.onclick=()=>addElement(b.dataset.type);b.ondragstart=e=>{dragType=b.dataset.type;e.dataTransfer.setData("text/plain",dragType)}});$("printPage").ondragover=e=>e.preventDefault();$("printPage").ondrop=e=>{e.preventDefault();const r=$("printPage").getBoundingClientRect(),type=e.dataTransfer.getData("text/plain")||dragType;let field="";let t=type;if(type.startsWith("field:")){t="field";field=type.slice(6)}addElement(t,(e.clientX-r.left)/(zoom/100)/MM,(e.clientY-r.top)/(zoom/100)/MM,field)};$("printPage").onclick=()=>{selected.clear();renderElements();renderLayers();syncProps()};
for(const id of ["propX","propY","propW","propH","propText","propField","propFontSize","propWeight"])$(id).addEventListener("input",updateProps),$(id).addEventListener("change",()=>{updateProps();pushHistory();autoSave()});document.querySelectorAll("[data-align]").forEach(b=>b.onclick=()=>{const e=selectedOne();if(!e)return;e.align=b.dataset.align;renderElements();syncProps();pushHistory();autoSave()});
$("duplicateBtn").onclick=duplicate;$("deleteBtn").onclick=del;$("lockBtn").onclick=()=>toggleKey("locked");$("hideBtn").onclick=()=>toggleKey("hidden");$("frontBtn").onclick=()=>moveLayer(true);$("backBtn").onclick=()=>moveLayer(false);$("applyPage").onclick=()=>applyPage(true);$("pagePreset").onchange=e=>{if(e.target.value!=="custom"){const [w,h]=e.target.value.split("x");$("pageW").value=w;$("pageH").value=h;applyPage(true)}};$("gridToggle").onchange=e=>{$("printPage").classList.toggle("grid-on",grid=e.target.checked)};$("snapToggle").onchange=e=>snap=e.target.checked;$("safeToggle").onchange=e=>$("safeGuide").classList.toggle("hidden",!e.target.checked);$("zoomRange").oninput=e=>setZoom(e.target.value);$("zoomOut").onclick=()=>setZoom(zoom-5);$("zoomIn").onclick=()=>setZoom(zoom+5);$("previewBtn").onclick=()=>setPreview(!preview);$("printBtn").onclick=testPrint;$("saveBtn").onclick=()=>{autoSave();toast("模板已保存")};$("templateName").onchange=autoSave;$("undoBtn").onclick=()=>restore(hIndex-1);$("redoBtn").onclick=()=>restore(hIndex+1);$("fullBtn").onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{toast("浏览器未允许全屏")}};$("newBtn").onclick=()=>{const t=createTemplate();state.templates.push(t);state.activeTemplateId=t.id;history=[];hIndex=-1;selected.clear();renderAll();pushHistory();autoSave()};$("fieldSearch").oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll(".field-item").forEach(n=>n.classList.toggle("hidden",!n.textContent.toLowerCase().includes(q)))};
$("contextMenu").onclick=e=>{const c=e.target.dataset.cmd;if(c==="duplicate")duplicate();if(c==="front")moveLayer(true);if(c==="back")moveLayer(false);if(c==="lock")toggleKey("locked");if(c==="delete")del();$("contextMenu").classList.add("hidden")};document.addEventListener("click",()=>$("contextMenu").classList.add("hidden"));document.addEventListener("keydown",e=>{const editing=["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName);if(e.ctrlKey&&e.key.toLowerCase()==="s"){e.preventDefault();autoSave();toast("模板已保存");return}if(e.ctrlKey&&e.key.toLowerCase()==="z"){e.preventDefault();restore(hIndex-1);return}if(e.ctrlKey&&e.key.toLowerCase()==="y"){e.preventDefault();restore(hIndex+1);return}if(editing)return;if((e.key==="Delete"||e.key==="Backspace")&&selected.size){e.preventDefault();del();return}if(e.ctrlKey&&e.key.toLowerCase()==="d"){e.preventDefault();duplicate();return}const step=e.shiftKey?5:1;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)&&selected.size){e.preventDefault();for(const x of current().elements.filter(v=>selected.has(v.id))){if(e.key==="ArrowLeft")x.x=Math.max(0,x.x-step);if(e.key==="ArrowRight")x.x+=step;if(e.key==="ArrowUp")x.y=Math.max(0,x.y-step);if(e.key==="ArrowDown")x.y+=step}renderElements();syncProps();pushHistory();autoSave()}})}
bind();load();setZoom(75);